### ISSUE TITLE
user access cloudconductor version >= 3.0

### ISSUE THREAD

**Issue by herz0g** [cinovo/cloudconductor-server#108]
Hi,

what is the default username / password for the UI access in Cloudconductor version 3.0 and above?
The property in /opt/cloudconductor/cloudconductor.properties isn't working like documented here: https://github.com/cinovo/cloudconductor-server/wiki/Installation. No matter what I insert into the properties file the database data stays the same. I checked the liquibase script and noticed that the salt and hash is hardcoded there - so it would be nice to get the default password for the admin user.

Beside that I started the UserTest Unit test and used the hash and salt from that test, inserted into the user table for the admin user and restarted the server - wasn't able to login with admin / password as well.

Regards

**Comment by YukiInu** [comment]
Hi,

the default password for the admin should be: admin
We will update the documentation.

Kind regards

**Comment by herz0g** [comment]
Hi,

that password is not working on a clean install, with a fresh database. Tried that multiple times.
