### ISSUE TITLE
value too long for type character varying(50)

### ISSUE THREAD

**Issue by herz0g** [cinovo/cloudconductor-server#115]
Hi,

noticed some errors during repo indexing if some metadata of a package is to long.

```
12:05:22,499 WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: 0, SQLState: 22001
12:05:22,500 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - ERROR: value too long for type character varying(50)
12:05:22,501 ERROR de.cinovo.cloudconductor.server.repo.IndexTask  - Error indexing repo
```

Reproduce:
* Store the package http://mirror.centos.org/centos/7/updates/x86_64/Packages/java-11-openjdk-devel-11.0.10.0.9-0.el7_9.x86_64.rpm in your package server
* The package will not show up in cloudconductor-server
* Errors in log (see above)

I did a rebuild of the rpm package and changed the values below, cc-server was able to index the package afterwards.

Provides:      application(java-11-openjdk-11.0.10.0.9-0.el7_9.x86_64-jconsole.desktop)
Provides:      application(java-11-openjdk-11.0.10.0.9)

Is there any reason why you don't use varchar255 ?

**Comment by YukiInu** [comment]
Hi. 
Thanks for bringing this up.
We also faced this problem some weeks ago and fixed it with commit https://github.com/cinovo/cloudconductor-server/commit/53e313bd6e651ebd5a80ace5f47033e799c04d55
and in version v3.7. Please note that you also need Agent version 3.4 for api compatibility reasons.

Kind regards
