### ISSUE TITLE
Server Log complains about SLOW RESPONSE, connection to agents lost

### ISSUE THREAD

**Issue by kkappel** [cinovo/cloudconductor-server#169]
Since Update of Server to 3.11, we lost connection to many Agents running with v.3.8
Online: 127 cc-agents
Offline and trying to connect: ca 50 cc-agents
database: RDS (postgres 11)
Server: AWS t3.xlarge
cmdline: /usr/lib/jvm/jre-1.8.0/bin/java -Xmx4096m ...bla
load average: 0.56, 0.90, 0.97

14:51:42,740 WARN  de.taimos.dvalin.jaxrs.monitoring.MonitoringFeature  - SLOW RESPONSE: Message 7df99f33-9225-4f5f-ba3c-032a968934d1 was 1032 ms inflight. Access was to class 'de.cinovo.cloudconductor.server.rest.agent.AgentImpl' and method 'public de.cinovo.cloudconductor.api.model.ServiceStatesChanges de.cinovo.cloudconductor.server.rest.agent.AgentImpl.notifyServiceState(java.lang.String,java.lang.String,de.cinovo.cloudconductor.api.model.ServiceStates,java.lang.String)' via URI '/api/agent/Production_3rd/noah2018/fcca6463-b38c-4cb0-ae28-452e59c494a8/service'
[...]
14:57:36,781 WARN  de.taimos.dvalin.jaxrs.monitoring.MonitoringFeature  - SLOW RESPONSE: Message 59dbb70c-068d-4603-92bc-e2930587fcdb was 1097 ms inflight. Access was to class 'de.cinovo.cloudconductor.server.rest.agent.AgentImpl' and method 'public de.cinovo.cloudconductor.api.model.PackageStateChanges de.cinovo.cloudconductor.server.rest.agent.AgentImpl.notifyPackageState(java.lang.String,java.lang.String,de.cinovo.cloudconductor.api.model.PackageState,java.lang.String)' via URI '/api/agent/Production_3rd/noah2018/2999588f-fd21-450d-bcfc-a723575299c6/package'
[...]
16:55:42,684 WARN  de.taimos.dvalin.jaxrs.monitoring.MonitoringFeature  - SLOW RESPONSE: Message f39edeef-7bfe-4a3d-8739-2a6cd8032ed6 was 1065 ms inflight. Access was to class 'de.cinovo.cloudconductor.server.rest.ui.ServiceUsageImpl' and method 'public java.util.Map de.cinovo.cloudconductor.server.rest.ui.ServiceUsageImpl.getServiceUsages()' via URI '/api/serviceusages'

**Comment by YukiInu** [comment]
See release notes: https://github.com/cinovo/cloudconductor-server/releases/tag/v3.11

"Due to cloudconductor-api update and a bugfix Cloudconductor-agent should be updated to v3.10"

Jackson version changed from 2.14 .0 to 2.15.2 which can result in the problems you are facing. Any errors on agent side?
Please update the agents.

The slow response warning happens when the response is over 1 second. this should not be a new issue.
The updates itself mostly only changed library dependencies and angular

**Comment by kkappel** [comment]
Thanks for the Info, Yukilnu.
