### ISSUE TITLE
Filter on Hosts Page unusable

### ISSUE THREAD

**Issue by kkappel** [cinovo/cloudconductor-server#170]
Trying to Filter on Hosts Page by Template:
For part of a second, the Filter works,
then second by second the displayed hosts vanish
ending with an empty list of hosts

Server: 3.11
Proxy: nginx
Browser Firefox 117.0.1 64-bit, Windows 10

**Comment by marc92w** [comment]
Hi @kkappel,

thanks for your bug report. This is a known issue of the host overview. I will implement a bugfix for the next version.

Best regards
