### ISSUE TITLE
How to fix: Duplicate key violation

### ISSUE THREAD

**Issue by kkappel** [cinovo/cloudconductor-server#172]
Server 3.11 faces several duplicate key errors a day. Of course, table packageversion shows no duplicate keys.

As this is our production server, would it help and be harmless, to reindex database tables?
Should cloudconductor server be stopped while reindexing?
Is there proffesional support for cloudconductor 3.11 available?

Thanks in advance,

Klaus Kappel
Senior Systems Engeneer
Westernacher Solutions, Berlin

```
wspostgresprod02=> select *, count c from cloudconductor.packageversion p group by p.id having count > 1;
 id | packageid | version | pkgname | c 
----------------------------
(0 rows)

24.1.2024:

[root@cc-prod log]# grep SQL cloudconductor.log
15:44:26,520 WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper {calledClass=de.cinovo.cloudconductor.server.rest.agent.AgentImpl, calledMethod=notifyPackageState, requestId=44c9b005-2a69-4e7c-bc1f-b9d222764e0b, requestURI=/api/agent/Production_Authorensystem/noah2018/b0c109d3-d34b-475f-a617-7603a5d6db35/package} - SQL Error: 0, SQLState: 23505
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109) ~[org.hibernate.hibernate-core-5.6.14.Final.jar:5.6.14.Final]
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[org.hibernate.hibernate-core-5.6.14.Final.jar:5.6.14.Final]
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "packageid_version"
[...]

```

**Comment by marc92w** [comment]
Hi @kkappel,

thanks for your message. Sorry but we can not provide individual support for CloudConductor on GitHub.

It looks like an agent reports duplicate packageversions (same package name and version), which are not allowed in the database. You could check which packages are installed on that machine, maybe some of them are interpreted as the same. 

If you found a general issue with the agent parsing your installed packages or the server mapping them, please provide more details on how to reproduce this behavior or create a pull request with a proposal for a bug fix.

Best regards
