### ISSUE TITLE
JDBC PostgreSQL API unusable

### ISSUE THREAD

**Issue by kkappel** [cinovo/cloudconductor-server#173]
Could you please update the jdbc driver for Postgresql:
regression: This release has 2 known regressions which make it unusable see the notes in 42.5.3. We advise people not to use 42.5.2.
https://jdbc.postgresql.org/changelogs/2023-01-31-42.5.2-release/

**Comment by marc92w** [comment]
Hi @kkappel,

thanks for the hint, we will update the JDBC driver together with dvalin in the next version :+1:

Best regards

**Comment by YukiInu** [comment]
Hi @kkappel 

with the new Version https://github.com/cinovo/cloudconductor-server/releases/tag/v3.12 this issue is fixed.
We updated to version 42.7.2

Kind regards

**Comment by kkappel** [comment]
Thanks a lot, @YukiInu!
