### ISSUE TITLE
Cannot save Server Options

### ISSUE THREAD

**Issue by scyv** [cinovo/cloudconductor-server#61]
There is always "Please fill in all the information." message when trying to save the options
![grabbed_20150112-125750](https://cloud.githubusercontent.com/assets/1648397/5702443/9f1ed262-9a5a-11e4-9976-e763456494a9.png)

**Comment by siglocpp** [comment]
This bug has been fixed in the latest commits.

**Comment by scyv** [comment]
Hey @siglocpp, nice to see cloudconductor living 👍
